### PR TITLE
277 add fallback pricing providers for resilience

### LINKED ISSUE #277: Add fallback pricing providers for resilience
The solver currently relies solely on one provider for token pricing. If that provider. is unavailable, rate-limited, or returns errors, quote generation fails entirely.

Implement fallback/redundant pricing sources to improve reliabilityhttps://github.com/openintentsframework/oif-solver/issues/labels

### PR DESCRIPTION
**Pull request by nahimterrazas**
feat: fallback support and defillama implementation
 
- Introduced a new pricing implementation using DeFiLlama API for real-time asset prices.
- Updated configuration to support fallback implementations in the pricing system.
- Enhanced PricingService to handle primary and fallback pricing providers.
- Added necessary tests for the new implementation and its configuration validation.

fix #277 

## Summary by CodeRabbit

* **New Features**
  * Added DeFiLlama as a new pricing provider with caching, token ID mappings, and optional fixed prices.
  * Introduced ordered fallback pricing providers; primary source will automatically fall back to configured providers.
  * Configuration now supports listing and ordering multiple fallback pricing implementations and includes centralized default token mappings.

* **Tests**
  * Expanded test coverage for pricing backends, fallback behavior, conversions, and configuration parsing.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: crates/solver-core/src/builder/mod.rs [hunk 1]
```diff
@@ -395,7 +395,40 @@ impl SolverBuilder {
...
+				component = "pricing",
+				primary = %primary_pricing,
+				fallback_count = %fallback_impls.len(),
+				"Pricing service initialized with fallbacks"
+			);
+			Arc::new(PricingService::new_with_fallbacks(
+				pricing_impl,
+				fallback_impls,
+			))
+		};
```
Comment (shahnami) [inline crates/solver-core/src/builder/mod.rs]: Can't we just do `Arc::new(PricingService::new(pricing_impl, fallback_impls))`

File: crates/solver-pricing/src/implementations/defillama.rs [hunk 2]
```diff
@@ -0,0 +1,1018 @@
+//! DeFiLlama pricing implementation for production use.
+//!
+//! This implementation provides real-time asset prices from DeFiLlama API.
+//! DeFiLlama is a free, open-source API with no rate limits for basic usage.
+//! Used as a fallback when CoinGecko is unavailable.
```
[the remark this answers is not in the document]
Comment (shahnami) [reply crates/solver-pricing/src/implementations/defillama.rs]: Not relevant, can be used as primary as well

File: crates/solver-pricing/src/implementations/defillama.rs [hunk 3]
```diff
@@ -0,0 +1,1018 @@
...
+
+		let cache_duration = config
+			.get("cache_duration_seconds")
+			.and_then(|v| v.as_integer())
+			.unwrap_or(60) as u64;
+
+		// Build token ID map - DeFiLlama uses coingecko IDs with "coingecko:" prefix
+		let mut token_id_map = HashMap::new();
+
+		// Default mappings using coingecko IDs
```
Comment (shahnami) [inline crates/solver-pricing/src/implementations/defillama.rs]: I'm not sure I understand why we need this?

File: crates/solver-pricing/src/implementations/defillama.rs [hunk 4]
```diff
@@ -0,0 +1,1018 @@
...
+	/// HTTP client for API requests
+	client: Client,
+	/// Base URL for the API
+	base_url: String,
+	/// Cache for price data
+	price_cache: Arc<RwLock<HashMap<String, PriceCacheEntry>>>,
+	/// Cache duration in seconds
+	cache_duration: u64,
+	/// Map of token symbols to DeFiLlama coin IDs (coingecko: prefix)
+	token_id_map: HashMap<String, String>,
```
Comment (shahnami) [inline crates/solver-pricing/src/implementations/defillama.rs]: What's the relation with coingecko here?

File: crates/solver-pricing/src/lib.rs [hunk 5]
```diff
@@ -162,42 +197,157 @@ impl PricingService {
...
+				}
+				tracing::warn!(
+					"Primary pricing provider failed for currency_to_wei: {}, trying fallbacks",
+					e
+				);
+			},
+		}
+
+		// Try fallbacks in order
+		for (idx, fallback) in self.fallbacks.iter().enumerate() {
```
[the remark this answers is not in the document]
Comment (nahimterrazas) [reply crates/solver-pricing/src/lib.rs]: since there are a little bit diference we can create a macro rule
