### PR TITLE
Admin endpoints

### LINKED ISSUE #266: Endpoint design docs (admin/config)
Specs for: add token, update networks/controllers/admin wallet, withdraw, approvals, config reads. Include request/response, validation, SIWE payload, error codes, persistence impacts.

### LINKED ISSUE #268: SIWE admin auth module
- Deliverables: SIWE verifier (`signature` + `contents`) with domain binding, nonce issuance/storage/TTL, expiry window; signer must match admin registry;
 
AC: middleware blocks invalid/replayed/expired signatures; nonce storage covers TTL and reuse prevention; tests for happy path, bad signature, wrong signer, replay. Effort: M. Deps: #267  .

### LINKED ISSUE #269: Admin config APIs (SIWE-protected)
Deliverables: endpoints to list/update tokens/networks/controllers backed by Redis config store; hot-reload into `token_manager`; auto-approve required settlement spenders when tokens added; audit log entries.  
  
AC:
- after adding a token, `/api/tokens` reflects it without restart; 
- SIWE enforced on all mutations; when adding tokens (or similar actions that require spender approvals), the backend should send the necessary on-chain approval transactions.
- approval txs emitted/recorded; 
- responses include version/etag; 
- audit log captured. 

Deps: #266 , #267 .

### LINKED ISSUE #270: Withdraw/funds API
Deliverables: endpoint to withdraw chain/token/amount/destination using solver-managed account; policy checks; status persisted; submitted via delivery.  

AC: validates destination/nonzero/balance; returns tx hash + status; audit log entry stored; tests for success, insufficient funds, bad signature. Effort: M. 

Deps: #267 #268

### PR DESCRIPTION
**Pull request by nahimterrazas**
# Summary

## Checklist

- [ ] Add a reference to related issues in the PR description.
- [ ] Add unit tests if applicable.

## Summary by CodeRabbit

* **New Features**
  * Expanded Admin API: nonce/types, balances, config, fees, gas, token management (add/remove/approve), withdrawals, and richer standardized responses (including EIP‑712 type info).
  * Protected admin writes require JWT bearer auth and EIP‑712‑signed payloads.
  * Token manager: native/ERC‑20 balance checks, withdrawals, and batch approvals across chains/tokens.
  * Configurable commission_bps and rate_buffer_bps affecting pricing/profitability; admin withdrawals toggle.

* **Documentation**
  * Updated Admin API docs, examples, and OpenAPI spec (api-spec/admin-api.yaml).

Closes #270
Closes #269
Closes #268
Closes #266

### CODE REVIEW

File: crates/solver-config/src/lib.rs [hunk 1]
```diff
@@ -291,6 +299,14 @@ fn default_gas_buffer_bps() -> u32 {
 	1000 // 10%
 }
 
+fn default_commission_bps() -> u32 {
+	0 // Disabled by default for backward compatibility
```
Comment (shahnami) [inline crates/solver-config/src/lib.rs]: Backwards compatibility?

File: crates/solver-core/src/engine/cost_profit.rs [hunk 2]
```diff
@@ -160,11 +160,18 @@ impl CostProfitService {
 		request: &solver_types::GetQuoteRequest,
 		context: &solver_types::ValidatedQuoteContext,
 		decimals_map: &std::collections::HashMap<InteropAddress, u8>,
+		rate_buffer_bps: u32,
 	) -> Result<
 		std::collections::HashMap<solver_types::InteropAddress, TokenAmountInfo>,
 		CostProfitError,
 	> {
 		use solver_types::SwapType;
+		if rate_buffer_bps >= 10000 {
```
Comment (shahnami) [inline crates/solver-core/src/engine/cost_profit.rs]: is this the equivalent of 100%?

File: crates/solver-service/src/apis/admin.rs [hunk 3]
```diff
@@ -108,6 +138,368 @@ pub async fn handle_get_nonce(
...
+///
+/// Returns current gas unit configuration.
+pub async fn handle_get_gas(
+	State(state): State<AdminApiState>,
+) -> Result<Json<GasConfigResponse>, AdminAuthError> {
+	let versioned = state.config_store.get().await.map_err(config_store_error)?;
+	Ok(Json(gas_config_response(&versioned.data.gas)))
+}
+
+/// POST /api/v1/admin/admins
```
Comment (shahnami) [inline crates/solver-service/src/apis/admin.rs]: This endpoint seems odd `/api/v1/admin/whitelist` maybe?

File: crates/solver-service/src/apis/admin.rs [hunk 4]
```diff
@@ -232,47 +615,61 @@ pub async fn handle_add_token(
...
+	if request.gas_buffer_bps > 10000 {
 		return Err(AdminAuthError::InvalidMessage(format!(
 			"Invalid gasBufferBps: {} exceeds maximum of 10000 (100%)",
-			request.contents.gas_buffer_bps
+			request.gas_buffer_bps
+		)));
+	}
+
+	// 2b. Validate commission_bps is reasonable (0-10000 = 0-100%)
+	if request.commission_bps > 10000 {
```
Comment (shahnami) [inline crates/solver-service/src/apis/admin.rs]: Do we need to add more validation here, it can still be set to `-10000` for example.

File: crates/solver-config/src/lib.rs (hunk 1 above)
Comment (nahimterrazas) [reply crates/solver-config/src/lib.rs]: actually w havent impelmented properly. now it is working

File: crates/solver-service/src/apis/admin.rs [hunk 5]
```diff
@@ -232,47 +615,61 @@ pub async fn handle_add_token(
...
+		AdminAuthError::InvalidMessage(format!(
+			"Invalid minProfitabilityPct: '{}' is not a valid decimal",
+			request.min_profitability_pct
+		))
+	})?;
 
-	// 3. Validate gas_buffer_bps is reasonable (0-10000 = 0-100%)
-	if request.contents.gas_buffer_bps > 10000 {
+	// 2. Validate gas_buffer_bps is reasonable (0-10000 = 0-100%)
+	if request.gas_buffer_bps > 10000 {
```
[the remark this answers is not in the document]
Comment (nahimterrazas) [reply crates/solver-service/src/apis/admin.rs]: bps fields are u32

File: crates/solver-service/src/apis/admin.rs [hunk 6]
```diff
@@ -284,28 +681,372 @@ pub async fn handle_update_fees(
...
+			if end > start {
+				return format!("{}[REDACTED]{}", &url[..start], &url[end..]);
+			}
+		}
+	}
+
+	url.to_string()
+}
+
+fn redact_query_params(query: &str) -> String {
```
[the remark this answers is not in the document]
Comment (nahimterrazas) [reply crates/solver-service/src/apis/admin.rs]: I can, I have to add a Regex dependency though
